# ================================+++++++++====================
#                 _                          __ _       
#     /\/\   __ _(_)_ __     ___ ___  _ __  / _(_) __ _ 
#    /    \ / _` | | '_ \   / __/ _ \| '_ \| |_| |/ _` |
#   / /\/\ \ (_| | | | | | | (_| (_) | | | |  _| | (_| |
#   \/    \/\__,_|_|_| |_|  \___\___/|_| |_|_| |_|\__, |
#                                                 |___/ 
# ================================+++++++++====================

# Monitor Rules
# monitorrule=name:eDP-1,width:1920,height:1080,refresh:60,x:0,y:0,scale:1,vrr:0,rr:0
monitorrule=name:DP-1,width:3840,height:2160,refresh:60,x:0,y:0,scale:1.5
monitorrule=name:HDMI-A-3,width:1920,height:1080,refresh:60,x:2560,y:0,scale:1

# Overview Setting
hotarea_size=10
enable_hotarea=1
ov_tab_mode=1
ov_no_resize=1
overviewgappi=10
overviewgappo=20

# Misc
cursor_size=24
cursor_theme=Bibata-Modern-Ice

xwayland_persistence=1
syncobj_enable=0
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
circle_layout=scroller
enable_floating_snap=1
snap_distance=20
cursor_hide_timeout=0
drag_tile_to_tile=1
single_scratchpad=1

# keyboard
repeat_rate=25
repeat_delay=600
numlockon=1
xkb_rules_layout=us
# xkb_rules_options=ctrl:nocaps
# xkb_rules_options=grp:alt_altgr_toggle,caps:hyper

# Trackpad 
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
mouse_natural_scrolling=0
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1
mouse_accel_profile=2
mouse_accel_speed=0.0
# scroll_button=274
# scroll_method=1

# Appearance
gappih=10
gappiv=10
gappoh=15
gappov=15
scratchpad_width_ratio=0.9
scratchpad_height_ratio=0.9
borderpx=0

# sub config load
source=./autostart.conf
source=./env.conf
source=./animation.conf
source=./layout.conf
source=./effect.conf
source=./bind.conf
source=./rule.conf


